import { useEffect, useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { useNavigate, useParams } from 'react-router-dom'
import { getAdminBlogs, saveBlog, uploadImage } from '../../services/contentService'
import RichTextEditor from '../../components/admin/RichTextEditor'

const BlogEditor = () => {
  const { id } = useParams(); const navigate = useNavigate(); const [error, setError] = useState(''); const [uploading, setUploading] = useState(false)
  const { register, control, handleSubmit, reset, setValue, formState: { isSubmitting } } = useForm({ defaultValues: { status: 'draft', content: '' } })
  useEffect(() => { if (id) getAdminBlogs().then((items) => { const item = items.find((entry) => entry.id === id); if (item) reset({ ...item, content: Array.isArray(item.content) ? item.content.map((paragraph) => `<p>${paragraph}</p>`).join('') : item.content }) }).catch(() => setError('Impossible de charger ce blog.')) }, [id, reset])
  const onImage = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { setValue('cover_image_url', await uploadImage(file, 'blog-images')) } catch { setError('Échec de l’upload de l’image.')} finally { setUploading(false) } }
  const onSubmit = async (values) => { try { await saveBlog(values, id); navigate('/admin/blogs') } catch { setError('Impossible d’enregistrer le blog. Vérifiez le schéma Supabase.')} }
  return <section className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-[#8A4B23]">CMS / Blog</p><h1 className="mt-3 text-4xl font-semibold">{id ? 'Modifier le blog' : 'Nouveau blog'}</h1><form onSubmit={handleSubmit(onSubmit)} className="mt-8 space-y-5 rounded-2xl border border-[#8A4B23]/10 bg-white p-6 lg:p-8"><Field label="Titre" name="title" register={register} required /><Field label="Résumé" name="excerpt" register={register} required /><div className="grid gap-5 md:grid-cols-2"><Field label="Catégorie" name="category" register={register} required /><Field label="Auteur" name="author" register={register} required /></div><label className="block text-sm font-semibold">Image de couverture<input type="file" accept="image/*" onChange={onImage} className="mt-2 block w-full text-sm font-normal" />{uploading && <span className="mt-1 block text-xs text-[#8A4B23]">Upload...</span>}</label><label className="block text-sm font-semibold">Contenu<Controller name="content" control={control} rules={{ required: true }} render={({ field }) => <div className="mt-2"><RichTextEditor value={field.value} onChange={field.onChange} /></div>} /></label><label className="block text-sm font-semibold">Statut<select {...register('status')} className="mt-2 w-full rounded-xl border border-[#8A4B23]/15 bg-[#FAF7F2] px-4 py-3 font-normal"><option value="draft">Brouillon</option><option value="published">Publié</option></select></label>{error && <p className="rounded-xl bg-[#8A4B23]/10 p-3 text-sm text-[#8A4B23]">{error}</p>}<button disabled={isSubmitting || uploading} className="rounded-xl bg-[#8A4B23] px-5 py-3 font-semibold text-white disabled:opacity-60">{isSubmitting ? 'Enregistrement...' : 'Enregistrer'}</button></form></section>
}
const Field = ({ label, name, register, required }) => <label className="block text-sm font-semibold">{label}<input {...register(name, { required })} className="mt-2 w-full rounded-xl border border-[#8A4B23]/15 bg-[#FAF7F2] px-4 py-3 font-normal outline-none focus:border-[#8A4B23]" /></label>
export default BlogEditor
